version: "3.8"
services:
  meta:
    image: ghcr.io/tullyliu/baikaldb:2433c927f1b8c0081eca82a1a6c5b2296d2ddf82
    command: meta
    ports:
      - "8010:8010"
  store:
    image: ghcr.io/tullyliu/baikaldb:2433c927f1b8c0081eca82a1a6c5b2296d2ddf82
    command: store
    depends_on: 
      - meta
  db: 
    image: ghcr.io/tullyliu/baikaldb:2433c927f1b8c0081eca82a1a6c5b2296d2ddf82
    command: db
    depends_on: 
      - meta
      - store
    ports: 
      - "28282:28282"